config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: 'pages#index'
  #
  # get '/oauth/callbrails roack', to: 'sessions#create'
  root to: 'pages#index'
  resources :breeds
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breed.rb
class Breed

  def get_cats
    response = RestClient.get('http://localhost:3000/v1/breeds?api_id=' + ENV['API_KEY'])
    result = JSON.parse(response.body)
    result
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  before_action do
    flash[:notice] = "Please log in to see the breeds" unless current_user
    redirect_to root_path unless current_user
  end

  def index
    @breed = Breed.new
    @cats = @breed.get_cats
  end

  def show

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    req_params = "client_id=#{ENV['oauth_token']}&client_secret=#{ENV['oauth_secret']}&code=#{params[:code]}&grant_type=authorization_code&redirect_uri=#{ENV['oauth_redirect_uri']}"
    response = JSON.parse RestClient.post("#{ENV['server_base_url']}/oauth/token", req_params)
    session[:access_token] = response['access_token']
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def new_oauth_token_path
    "#{ENV['server_base_url']}/oauth/authorize?client_id=#{ENV['oauth_token']}&redirect_uri=#{ENV['oauth_redirect_uri']}&response_type=code"
  end
end

app/views/breeds/index.html.erb
<div class="cats">
  <% @cats.each do |cat| %>
    <div class="cat">
      <%= cat['name'] %><br>
      <%= image_tag cat['image'] %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatAPIClient</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="nav">
      <%= link_to "Home", root_path, class: "home" %>
      <%= flash[:notice] %>
      <%= current_user.email if current_user %>
      <%= link_to "All Breeds", breeds_path, class: "nav-item" if current_user %>
      <%= link_to "Sign Up", new_user_registration_path, class: "nav-item" if !current_user %>
      <%= link_to "Sign In", new_user_session_path, class: "nav-item" if !current_user %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-item" if current_user %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Welcome Cat Lover!</h1>